### ISSUE TITLE
how u determine wich courses are free 7 days period?

### ISSUE THREAD

**Issue by johnfelipe** [dennislamcv1/CodioDataScience#1]

**Comment by dennislamcv1** [comment]
1. Select the Prof Cert or Specialization programme.
2.  You must see Free Trial for 7 days here as shown:

![2022-10-27_5-46-50](https://user-images.githubusercontent.com/39684447/198144789-1b30df70-f2db-4536-a060-651ebab3846f.jpg)

**Comment by johnfelipe** [comment]
But Wich one is free today for example?

**Comment by dennislamcv1** [comment]
There are no days set which is free. You can type "Free" in Coursera Search box on top.
